# Generated by Django 3.1.7 on 2021-10-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectsubscribe',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='subjectsubscribe',
            old_name='subjectid',
            new_name='SubjectID',
        ),
        migrations.RenameField(
            model_name='subjectsubscribe',
            old_name='subscribe',
            new_name='Subscribe',
        ),
    ]
