# Generated by Django 3.1.7 on 2021-10-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_auto_20211027_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectid', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('attachment', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectid', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('attachment', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='subjectsubscribe',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='subjectsubscribe',
            old_name='SubjectID',
            new_name='subjectid',
        ),
        migrations.RenameField(
            model_name='subjectsubscribe',
            old_name='Subscribe',
            new_name='subscribe',
        ),
    ]
