# Generated by Django 3.1.7 on 2021-10-28 14:27

from django.db import migrations, models
import elearn.utils
import elearn.validators


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_auto_20211028_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attachment',
            field=models.FileField(null=True, upload_to=elearn.utils.upload_to, validators=[elearn.validators.validate_video_extension]),
        ),
        migrations.AlterField(
            model_name='video',
            name='attachment',
            field=models.FileField(null=True, upload_to=elearn.utils.upload_to, validators=[elearn.validators.validate_video_extension]),
        ),
    ]
