# Generated by Django 3.1.7 on 2021-11-01 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearn', '0006_auto_20211031_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('username', models.CharField(max_length=20, null=True)),
                ('subjectID', models.ManyToManyField(to='elearn.SubjectSubscribe')),
                ('userID', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
