# Generated by Django 3.1.7 on 2021-11-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.subjectsubscribe'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.subjectsubscribe'),
        ),
    ]
