# Generated by Django 3.1.7 on 2021-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0008_auto_20211103_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploader',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.CharField(default='', max_length=100),
        ),
    ]
