# Generated by Django 3.1.7 on 2021-11-05 11:39

from django.conf import settings
from django.db import migrations, models
import elearn.utils
import elearn.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearn', '0009_auto_20211103_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attachment',
            field=models.FileField(null=True, upload_to=elearn.utils.upload_to, validators=[elearn.validators.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('subjectid', models.ManyToManyField(to='elearn.SubjectSubscribe')),
                ('userid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
